<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/login.css">

    <title>Login</title>
</head>
<body>
    <div class="container">
        <form class="login" action="" method="">
            <input type="email" name="email" placeholder="Email">
            <input type="text" name="password" placeholder="Password">
            <div class="flex">
                <input class="btn" type="submit" value="entrar">
            </div>
            <p>Não tem conta?<a href="/register">Cadastre-se</a></p>
        </form>
</body>
</html

