<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/login.css">

    <title>Login</title>
</head>
<body>
    <div class="container">
        <form class="login" action="login/login" method="POST">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <h1>NOTEFLIX</h1>
            <input type="email" name="email" placeholder="Email">
            <input type="password" name="password" placeholder="Password">
            <div class="flex">
                <input class="btn" type="submit" value="entrar">
            </div>
            <p class="fontColor">Não tem conta?⠀<a href="/register">Cadastre-se</a></p>
        </form>
    </div>
</body>
</html

