<?php

function showNotes($movieId, $movieName, $movieNote, $movieDescription) {
    echo "<div class='ratings'>";
    echo "    <p class='name'>Nome: $movieName</p>";
    echo "    <p>Nota: $movieNote</p>";
    echo "    <p>Descrição: $movieDescription</p>";
    echo "    <form class='buttons' action='myRatings/delete' method='POST'>";
    echo "        <button type='submit' class='btn1' name='btn1'>Editar</button>";
    echo "        <button type='submit' class='btn2' name='btn2' value='$movieId'>Excluir</button>";
    echo "    </form>";
    echo "</div>";
} 
?>

<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/myRatings.css">
    <link rel="stylesheet" href="public/css/navbar.css">

    <title>My ratings</title>
</head>
<body>
    <div class="allPage">
        <div class="navbar">
        <a href="/rateMovies"><img class="logo" src="public/img/starLogo.png"></img></a>
            <p class="userRates">Minhas Avaliações</p>
            <a href="/login/logout"><p class="exit">Sair</p></a>
        </div>
        <div class="container">
            <span>Olá, <?= $user['name_user']  ?></span>

            <?php 
                foreach($allNotes as $notes) {
                    $movieId = $notes['id_note'];
                    $movieName = $notes['movie_name'];
                    $movieNote = $notes['movie_note'];
                    $movieDescription = $notes['movie_description'];

                    echo showNotes($movieId, $movieName, $movieNote, $movieDescription);
                }
            ?>
            
        </div>
    </div>
</body>
</html>


