<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/myRatings.css">
    <link rel="stylesheet" href="public/css/navbar.css">

    <title>My ratings</title>
</head>
<body>
    <div class="allPage">
        <div class="navbar">
        <a href="/rateMovies"><img class="logo" src="public/img/starLogo.png"></img></a>
            <p class="userRates">Minhas Avaliações</p>
            <a href="/login"><p class="exit">Sair</p></a>
        </div>
        <div class="container">
            <span>Olá, ...</span>
            <div class="ratings">
                <p class="name">Nome:</p>
                <p>Nota:</p>
                <p>Descrição:  aadsada dasdasd asdada aadsada da  aadsada dasdasd asdada aadsada da aadsada dasdasd asdada aadsada da aadsada dasdasd asdada aadsada da aadsada dasdasd asdada aadsada da aadsada dasdasd asdada aadsada dasdasd asdada aadsada dasdasd asdada aadsada dasdasd asdada aadsada dasdasd asdada aadsada dasdasd asdadas</p>
                <div class="buttons">
                    <button class="btn1">Editar</button>
                    <button class="btn2">Excluir</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>