<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/rateMovies.css">
    <link rel="stylesheet" href="public/css/navbar.css">

    <title>Rate movies</title>
</head>
<body>
    <div class="allPage">
        <div class="navbar">
            <img class="logo" src="public/img/starLogo.png">
            <a href="/myRatings"><p class="userRates">Minhas Avaliações</p></a>
            <a href="/login"><p class="exit">Sair</p></a>
        </div>
        <div class="container">
            <form method="POST" action="rateMovies/insertNote">
                <p>Escolha um filme e dê uma nota!</p>
                <input type="text" name="movieName" placeholder="Nome do filme" required minlength="2" maxlength="30">
                <input type="text" name="note" onkeypress='return event.charCode >= 48 && event.charCode <= 57'placeholder="Dê uma nota de 1 a 10" required minlength="1" maxlength="2">
                <textarea type="text" name="description" placeholder="Descrição"required minlength="5" maxlength="400"></textarea>
                <input class="btn" type="submit" value="Enviar">
            </form>
        </div>
    </div>
</body>
</html>