<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/rateMovies.css">

    <title>Rate movies</title>
</head>
<body>
    <div class="allPage">
        <div class="navbar">
            <img class="logo" src="public/img/starLogo.png">
            <p class="userRates">Minhas Avaliações</p>
            <p class="exit">Sair</p>
        </div>
        <div class="container">
            <form>
                <p>Escolha um filme e dê uma nota!</p>
                <input type="text" placeholder="Nome do filme">
                <input type="number" placeholder="Nota">
                <textarea type="text" placeholder="Descrição"></textarea>
                <input class="btn" type="submit" value="Enviar">
            </form>
        </div>
    </div>
</body>
</html>