<?php 
    use App\Models\UserDB;
?>

<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/register.css">

    <title>Register</title>
</head>
<body>
    <div class="container">
        
            <?php 
            if(!empty($error['emailError'])) {
                echo $error['emailError'];
            }    
            ?>
        
        <form class="register" action="register/insert" method="POST">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <h1>NOTEFLIX</h1>
            <input type="email" name="email" placeholder="Email" required minlength="15" maxlength="60">
            <input type="text" name="username" placeholder="Nome" required minlength="3" maxlength="60">
            <input type="password" name="password" placeholder="Password" required minlength="8" maxlength="15">
            <div class="flex">
                <input class="btn" type="submit" value="Confirmar">
            </div>
            <p class="fontColor">Já tem conta?⠀<a href="/login">Entrar</a></p>
        </form>
    </div>
</body>
</html>