<!DOCTYPE html>
<html lang="pt_br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="public/css/register.css">

    <title>Register</title>
</head>
<body>
    <div class="container">
        <form class="register" action="" method="">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <h1>NOTEFLIX</h1>
            <input type="email" name="email" placeholder="Email">
            <input type="text" name="name" placeholder="Nome">
            <input type="text" name="password" placeholder="Password">
            <div class="flex">
                <input class="btn" type="submit" value="Confirmar">
            </div>
            <p class="fontColor">Já tem conta?⠀<a href="/login">Entrar</a></p>
        </form>
    </div>
</body>
</html>